{% set cxx_name = "libgazebo-yarp-plugins" %}
{% set plugin_name = "gazebo-yarp-plugins" %}
{% set name = "gazebo-yarp-plugins-split" %}
{% set version = "4.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/robotology/gazebo-yarp-plugins/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 144d92b92de20bf7e038d36f5f790541df967f7ea9e17a658a0f0e3ede5ef9c0

build:
  number: 0

outputs:
  - name: {{ cxx_name }}
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
      # See https://github.com/conda-forge/staged-recipes/pull/21891#issuecomment-1446115361
      missing_dso_whitelist:   # [win]
        - '*/CameraPlugin.dll'  # [win]
        - '*/DepthCameraPlugin.dll'  # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
        - multisheller
        # The project use yarpidl_thrift, so in cross-compilation we need it
        - libyarp  # [build_platform != target_platform]
      host:
        - libyarp
        - gazebo
        - libsdformat 9.*
        - libignition-math6
        - libprotobuf
        - tbb-devel
        - assimp
        - libopencv
        - ogre 1.10.*
        # Transitive public dependency of gazebo
        - dartsim-cpp
      run:

    test:
      commands:
        - test -f ${PREFIX}/include/GazeboYarpPlugins/common.h  # [not win]
        - if not exist %LIBRARY_INC%\\GazeboYarpPlugins\\common.h exit 1  # [win]
        - test -f ${PREFIX}/lib/cmake/GazeboYARPPlugins/GazeboYARPPluginsConfig.cmake  # [not win]
        # - if not exist %PREFIX%\\Library\CMake\\GazeboYARPPluginsConfig.cmake exit 1  # [win]
        {% set gyp_libs = [
                "inertial",
                "basestate",
                "lasersensor",
                "forcetorque",
                "configurationoverride",
                "linkattacher",
                "worldinterface",
                "externalwrench",
                "depthCamera",
                "camera",
                "videotexture",
                "imu",
                "robotinterface",
                "clock",
                "multicamera",
                "controlboard",
                "showmodelcom",
                "modelposepublisher",
                "contactloadcellarray"
        ] %}
        {% for gyp_lib in gyp_libs %}
        - test -f ${PREFIX}/lib/libgazebo_yarp_{{ gyp_lib }}${SHLIB_EXT}  # [unix]
        # - echo "Testing existance of %LIBRARY_BIN%\\gazebo_yarp_{{ gyp_lib }}.dll"  # [win]
        - if not exist %LIBRARY_BIN%\\gazebo_yarp_{{ gyp_lib }}.dll exit 1  # [win]
        {% endfor %}

  - name: {{ plugin_name }}
    requirements:
      run:
        - {{ pin_subpackage(cxx_name, exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/include/GazeboYarpPlugins/common.h  # [not win]
        - if not exist %LIBRARY_INC%\\GazeboYarpPlugins\\common.h exit 1  # [win]

about:
  home: https://github.com/robotology/gazebo-yarp-plugins
  license: LGPL-3.0-only
  license_file: LGPL3.TXT
  summary: 'Plugins to interface Gazebo with YARP. '

extra:
  feedstock-name: gazebo-yarp-plugins
  recipe-maintainers:
    - traversaro
